### ISSUE TITLE
Fix update-dependency to constrain to requirements.txt

### ISSUE THREAD

**Issue by lfse-slafleur** [Project-OMOTES/template-python#15]
Add in ci/{linux,windows}.update_dependencies.{sh,cmd} on second line:
```
-c requirements.txt
```

**Comment by MichielTukker** [comment]
I'm note sure why having an additional constraints.txt file is needed? it doesn't seem useful for the template?    `ci/{linux,windows}.update_dependencies.{sh,cmd}`  only updates the requirements.txt files based on `pyproject.toml`.  

Also, I would expect additional version constraints to come from a `contraints.txt`, instead of a `requirements.txt`? 

The only interface between projects is the celery-worker,  and I don't see how we will have version conflicts between dependencies there?
